### ISSUE TITLE
Challenge Request

### ISSUE THREAD

**Issue by nelsonmfinda** [leandrotk/ui-challenges#2]
Hi @leandrotk :nerd_face: 
I want to request a challenge, to pratice my HTML and CSS skills. Thanks!

**Comment by leandrotk** [comment]
@nelsonmfinda, thanks! Let me know about the challenge. Something like an URL for the UI, for example. Then I can add to the project.

**Comment by leandrotk** [comment]
@nelsonmfinda Let me know if you still want to request a challenge

**Comment by nelsonmfinda** [comment]
Yes, @leandrotk ! I want, sorry.

**Comment by leandrotk** [comment]
Ok. I will close this issue. As soon as you have the UI as an example, we can reopen this issue and add the new challenge :)
